require:
  - rubocop-airbnb

inherit_from:
  - .rubocop_todo.yml

# 追記
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.5.0
  DisplayStyleGuide: true
  Exclude: 
    - 'db/**/*'
    - 'config/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/_force_reload.rake'
    - 'bin/**/*'

# ブロック内の行数
Metrics/BlockLength:
  Exclude: 
    - 'spec/**/*'
# Airbnb / ModuleMethodInWrongFileの設定解除
ModuleMethodInWrongFile:
  Enabled: false
# メソッド名のprefixに「set_」「get_」を許可しない
AccessorMethodName:
  Enabled: true